#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""Stage vllm/*.py diffs vs BASE_TAG into a dist-packages overlay + Dockerfile."""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path

SITE_PREFIX = Path("usr/local/lib/python3.12/dist-packages")
DEFAULT_BASE_TAG = "v0.29.0"
DEFAULT_BASE_IMAGE = "vllm/vllm-openai:v0.29.0"


def git(*args: str) -> str:
    return subprocess.check_output(["git", *args], text=True).strip()


def changed_vllm_py_files(base_tag: str) -> list[str]:
    out = git("diff", "--name-only", f"{base_tag}..HEAD", "--", "vllm/")
    files = [line for line in out.splitlines() if line.endswith(".py")]
    if not files:
        raise SystemExit(f"no vllm/*.py changes vs {base_tag}")
    return files


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-tag", default=DEFAULT_BASE_TAG)
    parser.add_argument("--base-image", default=DEFAULT_BASE_IMAGE)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
    )
    args = parser.parse_args()

    repo_root = Path(git("rev-parse", "--show-toplevel"))
    out_dir = args.out_dir.resolve()
    overlay_root = out_dir / "overlay"
    if overlay_root.exists():
        shutil.rmtree(overlay_root)
    overlay_root.mkdir(parents=True)

    files = changed_vllm_py_files(args.base_tag)
    patch_rev = git("rev-parse", "--short", "HEAD")

    for rel in files:
        src = repo_root / rel
        dst = overlay_root / SITE_PREFIX / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

    dockerfile = out_dir / "Dockerfile.gen"
    dockerfile.write_text(
        "\n".join(
            [
                "# Auto-generated by gen_overlay.py",
                "# Thin COPY overlay on official base — no pip reinstall.",
                f"FROM {args.base_image}",
                "",
                f"ARG FLOWGPT_BASE_TAG={args.base_tag}",
                f"ARG FLOWGPT_PATCH_REV={patch_rev}",
                f"ARG FLOWGPT_PATCH_FILES={len(files)}",
                "",
                "COPY overlay/ /",
                "",
                'LABEL flowgpt.base="${FLOWGPT_BASE_TAG}" \\',
                '      flowgpt.patch.rev="${FLOWGPT_PATCH_REV}" \\',
                '      flowgpt.patch.files="${FLOWGPT_PATCH_FILES}"',
                "",
            ]
        )
    )

    manifest = out_dir / "overlay.manifest"
    manifest.write_text("\n".join(files) + "\n")
    print(f"patch_rev={patch_rev} files={len(files)}")
    print(f"wrote {dockerfile}")
    print(f"wrote {manifest}")


if __name__ == "__main__":
    main()
