FROM vllm/vllm-openai:v0.9.1

WORKDIR /app/vllm

# 安装依赖
RUN apt-get update && apt-get install -y git curl vim && rm -rf /var/lib/apt/lists/*

# ✅ 添加 numpy 依赖（否则 torch 会报错找不到 numpy）
RUN pip install numpy
# 拷贝你的 vllm 源码与模型
COPY vllm /app/vllm

# 暴露端口
EXPOSE 8000

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.api_server"]

# 启动命令
CMD [\
  "--model", "kaonai/Qwen3-0.6B-rm",\
  "--served-model-name", "Qwen3-0.6B-rm",\
  "--root-path", "/api",\
  "--task", "embedding",\
  "--trust-remote-code",\
  "--port", "8000",\
  "--enforce-eager"\
]